import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import * as jose from "jose";
import axios from "axios";
import { GetServerSideProps } from "next";
import Link from "next/link";

// export default function Home() {
//   const [data, setData] = useState();

//   const fetchAPI = async () => {
//     let utf8Encode = new TextEncoder();
//     const secretKey = utf8Encode.encode("your-256-bit-secret");

//     // const jwt = await new jose.SignJWT({
//     //   language: "en",
//     // })
//     //   .setProtectedHeader({
//     //     alg: "HS512",
//     //     kid: "78623e77-5c42-4615-a640-58a88d0d2080",
//     //     typ: "JWT",
//     //   })
//     //   .setIssuedAt("1661766988")
//     //   .sign(secretKey);

//     // console.log(jwt);

//     const jwt =
//       "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCIsImtpZCI6Ijc4NjIzZTc3LTVjNDItNDYxNS1hNjQwLTU4YTg4ZDBkMjA4MCJ9.eyJpYXQiOiIxNjYxNzY2OTg4IiwibGFuZ3VhZ2UiOiJlbiJ9.9EeE0b01OV3vEq_2UuOm6kFLNCdZPcUCzxdhk5PtPoKsjq9jUJIJWLJemVXDn26sfGvMHrUxpJLlh2zOLu45Uw";

//     const res = await axios.post(
//       "https://apitest.oneibc.com/frontend/v3/services/1/products",
//       jwt
//     );

//     const data = res.data;

//     // console.log(data);

//     const claims = jose.decodeJwt(data);
//     // console.log(claims);

//     setData(claims);

//     // Object.keys(clams && clams.data && clams.data.topProducts).forEach(
//     //   (value) =>
//     //   {
//     //     console.log(clams.data.topProducts[item]);

//     //   }
//     // );
//     Object.keys(claims).forEach((value) => {
//       if (value == "data") {
//         Object.keys(claims[value]).forEach((item) => {
//           if (item == "topProducts") {
//             Object.keys(claims[value][item]).forEach((idx) => {
//               console.log(claims[value][item][idx]["areaId"]);
//             });
//           }
//         });
//       }
//     });
//   };

//   useEffect(() => {
//     fetchAPI();
//   }, []);

//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <h1 className={styles.title}>
//           Welcome to <a href="https://nextjs.org">Next.js!</a>
//         </h1>

//         <p className={styles.description}>
//           Get started by editing{" "}
//           <code className={styles.code}>pages/index.js</code>
//         </p>

//         <p>
//           {Object.keys((data && data.data.minPrice) || {}).map((value, id) => {
//             return <p key={id}>{data.data.minPrice[value]}</p>;
//           })}
//         </p>
//         {/* {Array.from(infos.topProducts || []).map((item) => {
//           return (
//             <div key={item.areaId}>
//               <h2>{item.title}</h2>
//               <img src={item.image} alt="" />
//               <img src={item.imageFill} alt="" />
//               {Array.from(item.countries || []).map((country, index) => (
//                 <div key={index}>
//                   <div onClick={() => Router.push(`/nominees`)}>
//                     <p>{country.name}</p>
//                     <img src={country.imageJuris} alt="" />
//                   </div>
//                 </div>
//               ))}
//             </div>
//           );
//         })} */}
//       </main>

//       <footer className={styles.footer}>
//         <a
//           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Powered by{" "}
//           <span className={styles.logo}>
//             <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//           </span>
//         </a>
//       </footer>
//     </div>
//   );
// }

// export async function getServerSideProps() {
//   const companys = await fetchCompany();
//   return {
//     props: {
//       companys,
//     },
//   };
// }

export default function Home() {
  const [data, setData] = useState();
  const fetchCompany = async () => {
    let utf8Encode = new TextEncoder();
    const secretKey = utf8Encode.encode("your-256-bit-secret");

    // const jwt = await new jose.SignJWT({
    //   language: "en",
    // })
    //   .setProtectedHeader({
    //     alg: "HS512",
    //     kid: "78623e77-5c42-4615-a640-58a88d0d2080",
    //     typ: "JWT",
    //   })
    //   .setIssuedAt("1661766988")
    //   .sign(secretKey);

    // console.log(jwt);

    const jwt =
      "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCIsImtpZCI6Ijc4NjIzZTc3LTVjNDItNDYxNS1hNjQwLTU4YTg4ZDBkMjA4MCJ9.eyJpYXQiOiIxNjYxNzY2OTg4IiwibGFuZ3VhZ2UiOiJlbiJ9.9EeE0b01OV3vEq_2UuOm6kFLNCdZPcUCzxdhk5PtPoKsjq9jUJIJWLJemVXDn26sfGvMHrUxpJLlh2zOLu45Uw";

    const res = await axios.post(
      "https://apitest.oneibc.com/frontend/v3/services/1/products",
      jwt
    );

    const data = res.data;

    // console.log(data);

    const claims = jose.decodeJwt(data);

    setData(claims.data);

    console.log(claims.data);

    // Object.keys(clams && clams.data && clams.data.topProducts).forEach(
    //   (value) =>
    //   {
    //     console.log(clams.data.topProducts[item]);
    //   }
    // );
    // Object.keys(claims).forEach((value) => {
    //   if (value == "data") {
    //     Object.keys(claims[value]).forEach((item) => {
    //       if (item == "topProducts") {
    //         Object.keys(claims[value][item]).forEach((idx) => {
    //           console.log(claims[value][item][idx]["areaId"]);
    //         });
    //       }
    //     });
    //   }
    // });
  };

  useEffect(() => {
    fetchCompany();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div>
          {Object.keys((data && data.minPrice) || {}).map((value, id) => {
            return <p key={id}>{data.minPrice[value]}</p>;
          })}
        </div>
        {Object.keys((data && data.topProducts) || []).map((item, id) => {
          return (
            <div key={id}>
              {Object.keys(data.topProducts[item]).map((value, idx) => {
                if (value == "areaId") {
                  return (
                    <Link
                      href={`/product/${data.topProducts[item][value]}`}
                      key={idx}
                    >
                      Product
                    </Link>
                  );
                  // return <div key={idx}>{data.topProducts[item][value]}</div>;
                }
              })}
            </div>
            // <div key={item.areaId}>
            //   <h2>{item.title}</h2>
            //   <img src={item.image} alt="" />
            //   <img src={item.imageFill} alt="" />
            //   {Array.from(item.countries || []).map((country, index) => (
            //     <div key={index}>
            //       <div onClick={() => Router.push(`/nominees`)}>
            //         <p>{country.name}</p>
            //         <img src={country.imageJuris} alt="" />
            //       </div>
            //     </div>
            //   ))}
            // </div>
          );
        })}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
